./pyfile.py:57: RuntimeWarning: invalid value encountered in log
  mini = log(-10) + np.random.rand(Nens)*(log(10) - log(-10))
Traceback (most recent call last):
  File "./pyfile.py", line 130, in <module>
    errorpage(errval, "fanatapan@gmail.com", "http://localhost/results/ee606b9a18b785f2287d2248b8ec3b8d")
  File "/usr/local/lib/python2.7/dist-packages/theonlinemcmc/errorpage.py", line 36, in errorpage
    emailresponse(emailaddress, outdir, runerror=True)
  File "/usr/local/lib/python2.7/dist-packages/theonlinemcmc/emailresponse.py", line 56, in emailresponse
    server = smtplib.SMTP(edata['server'],25)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 13] Permission denied
